infra(detection-toiture-sync-it): add vgg verification instatus monitoring

diff --git a/.github/workflows/detection-toiture-sync-it.yml b/.github/workflows/detection-toiture-sync-it.yml
--- a/.github/workflows/detection-toiture-sync-it.yml
+++ b/.github/workflows/detection-toiture-sync-it.yml
@@ -13,6 +13,7 @@ env:
   IN_STATUS_500_TMPL_ID: ${{ secrets.INSTATUS_500_TMPL_ID }}
   IN_STATUS_RESOLVE_500_TMPL_ID: ${{ secrets.INSTATUS_RESOLVE_500_TMPL_ID }}
   IN_STATUS_VGG_EXCEPTION_TMPL_ID: ${{ secrets.IN_STATUS_VGG_EXCEPTION_TMPL_ID }}
+  IN_STATUS_RESOLVE_VGG_TMPL_ID: ${{ secrets.IN_STATUS_RESOLVE_VGG_TMPL_ID }}
   IN_STATUS_IMAGE_SOURCES_DEGRADED_TMPL_ID: ${{ secrets.IN_STATUS_IMAGE_SOURCES_DEGRADED_TMPL_ID }}
   IN_STATUS_IMAGE_SOURCES_RESTORED_TMPL_ID: ${{ secrets.IN_STATUS_IMAGE_SOURCES_RESTORED_TMPL_ID }}
 
@@ -49,6 +50,12 @@ jobs:
           .[]
           | select(.status != "RESOLVED" and
           (.name == "Internal server error"))
+          | "\(.id)|\(.name)|\(.status)"')
+          
+          vgg_incident_lines=$(echo "$incident_list" | jq -r '
+          .[]
+          | select(.status != "RESOLVED" and
+          (.name == "Unexpected obtained detection VGG result"))
           | "\(.id)|\(.name)|\(.status)"')
           
           image_performance_incident_lines=$(echo "$incident_list" | jq -r '
@@ -121,9 +128,38 @@ jobs:
             errors+=" original_image_url is actually null or empty"$'\n'
           fi
           
-          if [[ -n "$errors" ]]; then
-            echo "Response contains unexpected values :"
-            echo "$errors"
+          vgg_error=""
+          
+          if [[ -n "$vgg_file_url" ]]; then
+            expected_vgg=".github/workflows/examples/detection-toiture-response-example.json"
+          
+            curl -sf "$vgg_file_url" -o downloaded-vgg.json
+          
+              jq -r '
+              .[0]
+              | to_entries[0].value
+              | .regions
+              | to_entries[]
+              | .value.region_attributes.label
+              ' downloaded-vgg.json | sort | uniq -c > actual-vgg.txt
+          
+            jq -r '
+              .[0]
+              | to_entries[0].value
+              | .regions
+              | to_entries[]
+              | .value.region_attributes.label
+              ' "$expected_vgg" | sort | uniq -c > expected-vgg.txt
+          
+            if ! diff actual-vgg.txt expected-vgg.txt > /dev/null; then
+              vgg_error+="Unexpected number of regions per label in vgg_file"$'\n'
+            fi
+          fi
+          
+          if [[ -n "$errors" || -n "$vgg_error" ]]; then
+            echo "Response contains unexpected values"
+            echo "general errors : $errors"
+            echo "vgg error : $vgg_error"
             if [[ -z "$internal_incident_lines" ]]; then
               echo "No active 'Internal server error' incident. Creating one..."
               in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" \
@@ -134,6 +170,15 @@ jobs:
               echo "InStatus incident identifier: '$incident_id'"
             else
                 echo "Incident already exists. Not creating another one."
+            fi
+            if [[ -z "$vgg_incident_lines" ]]; then
+              echo "No active 'Unexpected obtained detection VGG result' incident. Creating one..."
+              in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" \
+              -X POST https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_VGG_EXCEPTION_TMPL_ID \
+              -H "Authorization: Bearer $IN_STATUS_API_KEY")
+          
+              incident_id=$(jq -r '.id' in-status-response.json)
+              echo "InStatus incident identifier: '$incident_id'"
             fi
             exit 1
           else
@@ -146,6 +191,16 @@ jobs:
                   -H "Authorization: Bearer $IN_STATUS_API_KEY"
                 fi
               done <<< "$internal_incident_lines"
+            fi
+            if [[ -n "$vgg_incident_lines" ]]; then
+              while IFS='|' read -r id incident_name incident_status; do
+                if [[ "$incident_name" == *"Unexpected obtained detection VGG result"* ]]; then
+                  echo "Resolving unexpected obtained detection VGG result incident: $id"
+                  curl -s -o /dev/null -X POST \
+                  https://api.instatus.com/v2/$IN_STATUS_PAGE_ID/incidents/"$id"/incident-updates/$IN_STATUS_RESOLVE_VGG_TMPL_ID \
+                  -H "Authorization: Bearer $IN_STATUS_API_KEY"
+                fi
+              done <<< "$vgg_incident_lines"
             fi
             if [[ -n "$image_performance_incident_lines" ]]; then
               while IFS='|' read -r id incident_name incident_status; do
