infra: add INSTATUS monitoring in detection sync github actions IT worflow

diff --git a/.github/workflows/detection-creation-it.yml b/.github/workflows/detection-creation-it.yml
--- a/.github/workflows/detection-creation-it.yml
+++ b/.github/workflows/detection-creation-it.yml
@@ -8,6 +8,10 @@ on:
 env:
   API_URL: ${{ secrets.DETECTION_API_URL }}
   API_KEY: ${{ secrets.DETECTION_API_KEY }}
+  IN_STATUS_PAGE_ID: ${{ secrets.INSTATUS_PAGE_ID }}
+  IN_STATUS_API_KEY: ${{ secrets.INSTATUS_API_KEY }}
+  IN_STATUS_500_TMPL_ID: ${{ secrets.INSTATUS_500_TMPL_ID }}
+  IN_STATUS_RESOLVE_500_TMPL_ID: ${{ secrets.INSTATUS_RESOLVE_500_TMPL_ID }}
 
 jobs:
   detection-creation:
@@ -90,8 +94,38 @@ jobs:
             errors+=" original_image_url is actually null or empty"$'\n'
           fi
           
+          incident_list=$(curl -s -X GET "https://api.instatus.com/v1/$IN_STATUS_PAGE_ID/incidents" \
+            -H "Authorization: Bearer $IN_STATUS_API_KEY")
+            incident_lines=$(echo "$incident_list" | jq -r '
+            .[]
+            | select(.status != "RESOLVED" and
+            (.name == "Internal server error"))
+            | "\(.id)|\(.name)|\(.status)"')
+          
           if [[ -n "$errors" ]]; then
+            if [[ -n "$incident_lines" ]]; then
+              while IFS='|' read -r id incident_name incident_status; do
+                echo "Incident : $incident_name ($incident_status)"
+                if [ "$incident_name" != "Internal Server Error" ]; then
+                  in_status_response=$(curl -s -o in-status-response.json -w "%{http_code}" -X POST $in_status_api_url/v1/$IN_STATUS_PAGE_ID/incidents/$IN_STATUS_500_TMPL_ID \
+                  -H "Authorization: Bearer $IN_STATUS_API_KEY")
+                  incident_id=$(jq -r '.id' in-status-response.json)
+                  echo "InStatus incident identifier: '$incident_id'"
+                  exit 1
+                fi
+              done <<< "$incident_lines"
+            fi
             echo "Response contains unexpected values :"
             echo "$errors"
             exit 1
+          else
+            if [[ -n "$incident_lines" ]]; then
+              while IFS='|' read -r id incident_name incident_status; do
+                if [[ "$incident_name" == "Internal server error" ]]; then
+                  curl -s -o /dev/null -X POST $in_status_api_url/v2/$IN_STATUS_PAGE_ID/incidents/"$id"/incident-updates/$IN_STATUS_RESOLVE_500_TMPL_ID \
+                  -H "Authorization: Bearer $IN_STATUS_API_KEY"
+                  echo "Resolving internal server error incident : $id"
+                fi
+              done <<< "$incident_lines"
+            fi
           fi
